apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: #Container로 배포할 Nginx image 이름
      - name: nginx
        image: alpine-nginx
        imagePullPolicy: IfNotPresent
        ports: # Container에서 사용할 포트 설정
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
---
apiVersion: v1
kind: Service # 외부와의 통신 방법 정의
metadata:
  annotations: # 클러스터 Load Balancer의 IP를 클러스터 내부의 오브젝트 간에 공유
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer # LoadBalancer 타입으로 정의
